server:
  port: 8033
spring:
  application:
    name: secondary-service

logging:
  level:
    com:
      logger:
        service: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
