# secondary-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: secondary-service-ingress
  namespace: app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: backend.log
      http:
        paths:
          - path: /secondary
            pathType: Prefix
            backend:
              service:
                name: secondary-service
                port:
                  number: 8033
